
import { PackingSlipHeader } from "./PackingSlipHeader";
import { PackingSlipDestination } from "./PackingSlipDestination";
import { PackingSlipItemsTable } from "./PackingSlipItemsTable";
import { PackingSlipCompliance } from "./PackingSlipCompliance";
import { PackingSlipSignatures } from "./PackingSlipSignatures";

interface SelectedItem {
  id: string;
  name: string;
  batchNumber?: string;
  selectedQuantity: number;
  productionDate?: string;
}

interface Customer {
  name: string;
  address?: string;
  contact_person?: string;
  phone?: string;
}

interface PackingSlipPreviewProps {
  packingSlipNumber: string;
  currentDate: string;
  destinationCustomer: Customer | null;
  selectedItems: SelectedItem[];
  totalItems: number;
  totalPackages: number;
  preparedBy: string;
  pickedUpBy: string;
}

export function PackingSlipPreview({
  packingSlipNumber,
  currentDate,
  destinationCustomer,
  selectedItems,
  totalItems,
  totalPackages,
  preparedBy,
  pickedUpBy,
}: PackingSlipPreviewProps) {
  return (
    <div className="bg-white p-8 border rounded-lg text-black">
      <PackingSlipHeader packingSlipNumber={packingSlipNumber} currentDate={currentDate} />
      
      <PackingSlipDestination destinationCustomer={destinationCustomer} currentDate={currentDate} />
      
      <PackingSlipItemsTable selectedItems={selectedItems} />
      
      {/* Summary */}
      <div className="mb-8">
        <h3 className="text-lg font-semibold mb-2">Summary:</h3>
        <p>Total Items: {totalItems}</p>
        <p>Total Packages: {totalPackages}</p>
      </div>
      
      <PackingSlipCompliance />
      
      <PackingSlipSignatures 
        preparedBy={preparedBy} 
        pickedUpBy={pickedUpBy} 
        currentDate={currentDate} 
      />
      
      {/* Footer */}
      <div className="text-center text-sm text-gray-500 border-t pt-4">
        <p>This document serves as official transport documentation for FAVV compliance</p>
        <p>Generated by TOTHAI Operations Management System</p>
      </div>
    </div>
  );
}
