
import jsPDF from 'jspdf';
import { format } from "date-fns";

export const addSummarySection = (pdf: jsPDF, totalItems: number, totalPackages: number, startY: number): number => {
  let yPos = startY + 15;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Summary:', 20, yPos);
  
  yPos += 10;
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Total Items: ${totalItems}`, 20, yPos);
  yPos += 7;
  pdf.text(`Total Packages: ${totalPackages}`, 20, yPos);
  
  return yPos;
};

export const addComplianceSection = (pdf: jsPDF, startY: number): number => {
  let yPos = startY + 20;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('FAVV Compliance:', 20, yPos);
  
  yPos += 10;
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text('✓ Full batch traceability', 25, yPos);
  yPos += 7;
  pdf.text('✓ Production dates recorded', 25, yPos);
  yPos += 7;
  pdf.text('✓ Transport documentation', 25, yPos);
  
  return yPos;
};

export const addSignatureSection = (pdf: jsPDF, preparedBy: string, pickedUpBy: string, currentDate: string, startY: number): number => {
  let yPos = startY + 25;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Prepared by:', 20, yPos);
  pdf.text('Picked up by:', 110, yPos);
  
  // Background boxes for signatures
  pdf.setFillColor(248, 250, 252);
  pdf.rect(20, yPos + 5, 80, 25, 'F');
  pdf.rect(110, yPos + 5, 80, 25, 'F');
  
  // Signature borders
  pdf.setDrawColor(229, 231, 235);
  pdf.rect(20, yPos + 5, 80, 25);
  pdf.rect(110, yPos + 5, 80, 25);
  
  yPos += 15;
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.text(preparedBy || "Not specified", 25, yPos);
  pdf.text(pickedUpBy || "Not specified", 115, yPos);
  
  yPos += 7;
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.text(`Electronisch ondertekend door ${preparedBy || "Not specified"}`, 25, yPos);
  pdf.text(`Electronisch ondertekend door ${pickedUpBy || "Not specified"}`, 115, yPos);
  
  yPos += 5;
  pdf.text(`Date: ${currentDate}`, 25, yPos);
  pdf.text(`Date: ${currentDate}`, 115, yPos);
  
  const currentTime = format(new Date(), "HH:mm");
  yPos += 5;
  pdf.text(`Time: ${currentTime}`, 25, yPos);
  pdf.text(`Time: ${currentTime}`, 115, yPos);
  
  return yPos;
};

export const addFooter = (pdf: jsPDF, startY: number) => {
  let yPos = startY + 20;
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text('This document serves as official transport documentation for FAVV compliance', 20, yPos);
  yPos += 4;
  pdf.text('Generated by TOTHAI Operations Management System', 20, yPos);
};
